blueprint:
  name: Night Motion-activated WLED Light
  description: Turn on a WLED light when motion is detected on night.
  domain: automation
  source_url: https://raw.githubusercontent.com/new-xmon-df/arduxmon-iot-projects/master/Projects/Smart%20WLED%20Lighting%20System%20with%20Motion%20Sensing%20for%20Hallways/home_assistant/blueprints/motion_light_wled.yaml
  author: Arduxmon
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    wled_light_target:
      name: WLED
      selector:
        target:
          entity:
            domain: light
    wled_light_palette:
      name: WLED palette
      selector:
        target:
          entity:
            domain: select
    wled_light_intensity:
      name: WLED intensity
      selector:
        target:
          entity:
            domain: number
    wled_light_speed:
      name: WLED speed
      selector:
        target:
          entity:
            domain: number
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
