blueprint:
  name: Night Motion-activated WLED Light - basic
  description: Turn on a WLED light when motion is detected on night.
  domain: automation
  source_url: https://github.com/new-xmon-df/arduxmon-iot-projects/blob/736c9521a5172a51d0bcf45b661cfc93f8ba7da0/Projects/Smart%20WLED%20Lighting%20System%20with%20Motion%20Sensing%20for%20Hallways/home_assistant/blueprints/motion_light_basic_wled.yaml
  author: Arduxmon
  input:
    motion_entity:
      name: "Motion Sensor"
      selector:
        entity:
          filter:
            device_class: motion
            domain: binary_sensor
    condition_toggle:
      name: "Consider Condition"
      description: Enter any conditions you would like to apply to the automation.
      default:
        - condition: sun
          before: sunrise
          after: sunset
          after_offset: "+00:30:00"
          enabled: false
      selector:
        condition:
    wled_light_target:
      name: "WLED light"
      selector:
        entity:
          filter:
            domain: light
            integration: wled
    wled_light_effect:
      name: "WLED effect"
      default: "Solid"
      selector:
        select:
          options:
            - Akemi
            - Android
            - Aurora
            - Black Hole
            - Blends
            - Blink
            - Blink Rainbow
            - Blobs
            - Blurz
            - Bouncing Balls
            - Bpm
            - Breathe
            - Candle
            - Candle Multi
            - Chase
            - Chase 2
            - Chase 3
            - Chase Flash
            - Chase Flash Rnd
            - Chase Rainbow
            - Chase Random
            - Chunchun
            - Colored Bursts
            - Colorful
            - Colorloop
            - Colortwinkles
            - Colorwaves
            - Crazy Bees
            - DJ Light
            - DNA
            - DNA Spiral
            - Dancing Shadows
            - Dissolve
            - Dissolve Rnd
            - Distortion Waves
            - Drift
            - Drift Rose
            - Drip
            - Dynamic
            - Dynamic Smooth
            - Fade
            - Fairy
            - Fairytwinkle
            - Fill Noise
            - Fire 2012
            - Fire Flicker
            - Firenoise
            - Fireworks
            - Fireworks 1D
            - Fireworks Starburst
            - Flow
            - Flow Stripe
            - Freqmap
            - Freqmatrix
            - Freqpixels
            - Freqwave
            - Frizzles
            - Funky Plank
            - GEQ
            - Game Of Life
            - Ghost Rider
            - Glitter
            - Gradient
            - Gravcenter
            - Gravcentric
            - Gravfreq
            - Gravimeter
            - Halloween Eyes
            - Heartbeat
            - Hiphotic
            - ICU
            - Juggle
            - Juggles
            - Julia
            - Lake
            - Lighthouse
            - Lightning
            - Lissajous
            - Loading
            - Matripix
            - Matrix
            - Metaballs
            - Meteor
            - Meteor Smooth
            - Midnoise
            - Multi Comet
            - Noise 1
            - Noise 2
            - Noise 3
            - Noise 4
            - Noise Pal
            - Noise2D
            - Noisefire
            - Noisemeter
            - Noisemove
            - Octopus
            - Oscillate
            - Pacifica
            - Palette
            - Percent
            - Perlin Move
            - Phased
            - Phased Noise
            - Pixels
            - Pixelwave
            - Plasma
            - Plasma Ball
            - Plasmoid
            - Polar Lights
            - Popcorn
            - Pride 2015
            - Puddlepeak
            - Puddles
            - Pulser
            - RSVD
            - RSVD
            - RSVD
            - RSVD
            - RSVD
            - RSVD
            - RSVD
            - RSVD
            - Railway
            - Rain
            - Rainbow
            - Rainbow Runner
            - Random Colors
            - Ripple
            - Ripple Peak
            - Ripple Rainbow
            - Rocktaves
            - Rolling Balls
            - Running
            - Running Dual
            - Saw
            - Scan
            - Scan Dual
            - Scanner
            - Scanner Dual
            - Scrolling Text
            - Sindots
            - Sine
            - Sinelon
            - Sinelon Dual
            - Sinelon Rainbow
            - Soap
            - Solid
            - Solid Glitter
            - Solid Pattern
            - Solid Pattern Tri
            - Spaceships
            - Sparkle
            - Sparkle Dark
            - Sparkle+
            - Spots
            - Spots Fade
            - Squared Swirl
            - Stream
            - Stream 2
            - Strobe
            - Strobe Mega
            - Strobe Rainbow
            - Sun Radiation
            - Sunrise
            - Sweep
            - Sweep Random
            - Swirl
            - TV Simulator
            - Tartan
            - Tetrix
            - Theater
            - Theater Rainbow
            - Traffic Light
            - Tri Fade
            - Tri Wipe
            - Twinkle
            - Twinklecat
            - Twinklefox
            - Twinkleup
            - Two Dots
            - Washing Machine
            - Waterfall
            - Waverly
            - Wavesins
            - Waving Cell
            - Wipe
            - Wipe Random
    wled_light_color:
      name: "WLED color"
      default: [255, 0, 0]
      selector:
        color_rgb:
    wled_light_brightness:
      name: "WLED brightness"
      default: 128
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: %
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  !input condition_toggle

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target:
      entity_id: !input wled_light_target
    data:
      effect: !input wled_light_effect
      brightness: !input wled_light_brightness
      rgb_color: !input wled_light_color
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target:
      entity_id: !input wled_light_target


